import { readdir, readFile, writeFile, mkdir, unlink } from 'node:fs/promises';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { marked } from 'marked';
import { parse } from 'yaml';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const GENERATED = '<!-- Generated by scripts/build.mjs; edit the Markdown source in _writing. -->';
export const escapeHTML = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const template = (source, values) => source.replace(/\{\{(\w+)\}\}/g, (_, key) => {
  if (!(key in values)) throw new Error(`Missing template value: ${key}`);
  return values[key];
});
const displayDate = date => new Intl.DateTimeFormat('en', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${date}T00:00:00Z`));

export function parsePost(source, filename) {
  const match = source.replace(/^\uFEFF/, '').match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)([\s\S]*)$/);
  if (!match) throw new Error(`${filename}: start with YAML metadata between --- lines.`);
  const metadata = parse(match[1]);
  for (const key of ['title', 'date', 'summary']) {
    if (typeof metadata?.[key] !== 'string' || !metadata[key].trim()) throw new Error(`${filename}: ${key} must be a nonempty string.`);
  }
  const { title, date, summary, draft = false } = metadata;
  const parsedDate = new Date(`${date}T00:00:00Z`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || Number.isNaN(parsedDate.valueOf()) || parsedDate.toISOString().slice(0, 10) !== date) {
    throw new Error(`${filename}: date must be a real date in YYYY-MM-DD format.`);
  }
  if (typeof draft !== 'boolean') throw new Error(`${filename}: draft must be true or false.`);
  const slug = basename(filename, '.md');
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error(`${filename}: use lowercase letters, numbers, and hyphens in the filename.`);
  if (!draft && !match[2].trim()) throw new Error(`${filename}: published posts need a body.`);
  return { title, date, summary, draft, slug, body: match[2], readingTime: Math.max(1, Math.ceil(match[2].trim().split(/\s+/).length / 220)) };
}

export async function build(root = ROOT) {
  const postDir = resolve(root, '_writing');
  const filenames = (await readdir(postDir)).filter(name => name.endsWith('.md')).sort();
  // Validate every post before changing any output. Drafts never produce article pages.
  const parsed = await Promise.all(filenames.map(async name => parsePost(await readFile(resolve(postDir, name), 'utf8'), name)));
  const posts = parsed.filter(post => !post.draft).sort((a, b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
  const [indexTemplate, postTemplate] = await Promise.all(['blog', 'post'].map(name => readFile(resolve(root, '_templates', `${name}.html`), 'utf8')));
  const emptyState = `<section class="empty-state" aria-labelledby="empty-heading">
      <span class="empty-mark" aria-hidden="true">✳</span>
      <h2 id="empty-heading">Nothing here just yet.</h2>
      <a class="text-link" href="research.html">Explore research <span aria-hidden="true">↗</span></a>
    </section>`;
  const list = posts.length ? `<ol class="post-list">${posts.map(post => `
      <li class="post-preview">
        <time datetime="${post.date}">${displayDate(post.date)}</time>
        <div><h2><a href="blog/${post.slug}.html">${escapeHTML(post.title)}</a></h2>
          <p>${escapeHTML(post.summary)}</p>
          <a class="text-link" href="blog/${post.slug}.html" aria-label="Read ${escapeHTML(post.title)}">Read post <span aria-hidden="true">↗</span></a>
        </div>
      </li>`).join('')}\n    </ol>` : emptyState;
  const outputs = new Map(posts.map(post => [`${post.slug}.html`, `${GENERATED}\n${template(postTemplate, {
    title: escapeHTML(post.title), description: escapeHTML(post.summary), date: post.date,
    displayDate: displayDate(post.date), readingTime: post.readingTime,
    // Markdown is authored by the site owner; raw HTML is supported intentionally.
    body: marked.parse(post.body),
  })}`]));

  // Embed existing JSON content at build time so all pages work without JavaScript.
  const publications = JSON.parse(await readFile(resolve(root, 'content/publications.json'), 'utf8'));
  const pages = await Promise.all([['index.html', 'about'], ['research.html', 'research'], ['resume.html', 'resume']].map(async ([file, key]) => {
    const data = { ...publications, ...JSON.parse(await readFile(resolve(root, `content/${key}.json`), 'utf8')) };
    const html = await readFile(resolve(root, file), 'utf8');
    const rendered = html.replace(/(<p\b[^>]*data-key="([^"]+)"[^>]*>)[\s\S]*?(<\/p>)/g, (_, start, key, end) => {
      if (!(key in data)) throw new Error(`${file}: missing content key ${key}`);
      return start + escapeHTML(data[key]) + end;
    });
    return [file, rendered];
  }));
  const outputDir = resolve(root, 'blog');
  await mkdir(outputDir, { recursive: true });
  // Remove only pages created by this builder when a post is deleted or becomes a draft.
  for (const filename of await readdir(outputDir)) {
    if (filename.endsWith('.html') && !outputs.has(filename)) {
      const path = resolve(outputDir, filename);
      if ((await readFile(path, 'utf8')).startsWith(GENERATED)) await unlink(path);
    }
  }
  for (const [filename, html] of outputs) {
    const path = resolve(outputDir, filename);
    const existing = await readFile(path, 'utf8').catch(error => { if (error.code !== 'ENOENT') throw error; return null; });
    if (existing !== null && !existing.startsWith(GENERATED)) throw new Error(`Refusing to overwrite hand-written page: ${path}`);
    await writeFile(path, html);
  }
  await writeFile(resolve(root, 'blog.html'), `${GENERATED}\n${template(indexTemplate, { title: 'Blog', description: 'Research notes, ideas, and things I learn along the way. A blog by Nima Dindarsafa.', posts: list })}`);
  for (const [filename, html] of pages) await writeFile(resolve(root, filename), html);
  return posts.length;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try { console.log(`Built site with ${await build()} published blog post(s).`); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
